apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: front-app
spec:
  containers:
  - name: frontend-app-container
    image: apiedade77/j1-frontend:latest
    ports:
    - containerPort: 3306